### ISSUE TITLE
Convolution layer in attentional head

### ISSUE THREAD

**Issue by vaesl** [prlz77/attend-and-rectify#1]
Thanks for the code you share! In the ECCV paper, it have shown that 1*1 convolution layer is used in attentional head but in the code it uses one 3*3 convolution layer to generate the attention heatmap. Could you please tell me why? Will it lead to better performance than 1*1 convolution?

**Comment by prlz77** [comment]
After submitting I noticed that on average 3x3 was better. You may find no difference at all though.

If computation and memory are not a critical thing for you, I'd recommend to use 3x3.

Pau

**Comment by vaesl** [comment]
Thanks for your reply! I will have a try for other task.

**Comment by prlz77** [comment]
Cool :)
